apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: search-indexing-kiii
type: Opaque
stringData:
  POSTGRES_USER: "emc"
  POSTGRES_PASSWORD: "emc"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: search-indexing-kiii
data:
  POSTGRES_DB: "searchindex"