apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: search-indexing-kiii
type: Opaque
stringData:
  JWT_SECRET_KEY: "BVSkdCitynkFzDMunkEINcGNGujPO7ORXnhkc/Lyg00="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: search-indexing-kiii
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/searchindex"
  SPRING_DATASOURCE_USERNAME: "emc"
  SPRING_DATASOURCE_PASSWORD: "emc"
  SPRING_PROFILES_ACTIVE: "dev"